# Generated by Django 4.0.6 on 2022-10-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automater', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='excel',
        ),
    ]
